---
all:
  hosts:
    ANS1:
      ansible_host: 192.168.78.21
    ANS2:
      ansible_host: 192.168.78.22
  children:
    routers:
      children:
        west:
          hosts:
            ANS1:
              ansible_host: 192.168.78.21
        east:
          hosts:
            ANS2:
              ansible_host: 192.168.78.22

