---

- name: Deploy a netconf configuration
  hosts: west
  gather_facts: False
  connection: netconf
  tasks:
    - name: Deploy the interface configuration
      netconf_config:
        xml: |
          <config>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <interface operation="replace">
                      <GigabitEthernet>
                  <name>1</name>
                          <description>OOB Management</description>
                                          <ip>
                              <vrf>
                      <forwarding>
                        <word>MGMT</word>
                      </forwarding>
                    </vrf>
                              <address>
                      <primary>
                        <address>192.168.78.21</address>
                        <mask>255.255.255.0</mask>
                      </primary>
                    </address>
                  </ip>
                          <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                      <GigabitEthernet>
                  <name>2</name>
                          <description>Link ANS1-to-ANS2</description>
                                           <ip>
                    <unnumbered>Loopback0</unnumbered>
                    <ospf xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ospf">
                      <network>point-to-point</network>
                    </ospf>
                  </ip>
                          <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                      <GigabitEthernet>
                  <name>3</name>
                                  <shutdown/>
                                  <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                      <GigabitEthernet>
                  <name>4</name>
                                  <shutdown/>
                                  <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                            <Loopback>
                  <name>0</name>
                  <description>ANS1-id</description>
                  <ip>
                    <address>
                      <primary>
                        <address>1.1.1.1</address>
                        <mask>255.255.255.255</mask>
                      </primary>
                    </address>
                  </ip>
                </Loopback>
                    </interface>
            </native>
          </config>
